### ISSUE TITLE
Where to find generated images on Android port?

### ISSUE THREAD

**Issue by dgrimes112** [EdVince/Stable-Diffusion-NCNN#15]
I have looked everywhere on my phone and I can't find where the app is installed nor where the images go after generation.

**Comment by EdVince** [comment]
we will not save the generated images in the app.

**Comment by dgrimes112** [comment]
> we will not save the generated images in the app.

Are they stored on the device at all? If so where?

**Comment by EdVince** [comment]
No, they are not stored and you can modify the android code yourself if you need it.
