### ISSUE TITLE
同prompt和seed下低分辨率和高分辨率生成差异大，有无办法缩小异变？

### ISSUE THREAD

**Issue by Baiyuetribe** [EdVince/Stable-Diffusion-NCNN#17]
最近体验了midjourney后，想尝试做成对话类的应用，主要适配AI绘本创作。
经过调整(随机值变为固定或有序)，同prompt和seed下，补充描述词可以生成几乎相近的图像，非常符合AI绘本的要求。
![image](https://user-images.githubusercontent.com/43716063/215986255-eec381d2-c253-44e5-8a27-ca6de9a0d10b.png)
### 问题
根据midjourney的模式，预先生成4张低分辨率的图，然后再选择优质的进行二次放大，这样有利于快速筛选优质结果和生成高质量成品。当我使用同一个prompt和seed生成的256图和512图，结果差异巨大，有无办法控制低分辨率到高点分辨率的异变效果？
![image](https://user-images.githubusercontent.com/43716063/215987297-aba44ee0-bbd3-40d8-88a0-748a49048096.png)
### 期待效果
![image](https://user-images.githubusercontent.com/43716063/215987862-2c10dfe3-de8a-495a-b576-4cb5bc410c7d.png)

**Comment by EdVince** [comment]
即便是同一个种子，不同分辨率下也会有不同的结果。因为很明显生成出来的256分辨率和512分辨率的初始随机图是不一样。你想做这种的话， 可以尝试把sampler从elura换成我代码里注释掉了的ddpm++2M karras，这个sampler只需要一个初始随机数。然后建议你再去看一下midjourney是怎么处理不同分辨率的随机数的问题的。

**Comment by eeyrw** [comment]
midjourney用的是多轮超分辨率的模式，和stable diffusion不一样。midjourney看到的大图实际上是超分辨率的结果。

**Comment by Baiyuetribe** [comment]
原来是这样啊，那我知道该怎么做了 👍
