### ISSUE TITLE
要有个比较稳定的模型转换工具那就牛X了

### ISSUE THREAD

**Issue by coollofty** [EdVince/Stable-Diffusion-NCNN#24]
这工程有意思，但要有个比较靠谱的工具，随便一个SD的模型都可以一个命令行就转出来，然后就可以用，那这个工程我觉得要起飞。。。。

**Comment by EdVince** [comment]
https://github.com/EdVince/diffusers-ncnn
这是我做的转换模型的仓库，你可以跟着走一遍就行了，跟着走一遍可以出来能用的模型。

**Comment by zylo117** [comment]
> https://github.com/EdVince/diffusers-ncnn 这是我做的转换模型的仓库，你可以跟着走一遍就行了，跟着走一遍可以出来能用的模型。

请问支持什么版本的呢？1.5和2.1都转换不了啊
