### ISSUE TITLE
Terminated

### ISSUE THREAD

**Issue by Fcucgvhhhvjv** [EdVince/Stable-Diffusion-NCNN#33]
Speed mode 1 in magic.txt doesn't work on x86_64 linux with 16 gb ram , it gets to the last step and gets terminated .
also the x86_64 linux executable seems to work for arm 64 devices I've checked in termux , but it can't generate  it gets killed somehow , I've even tried with 128x128 and step-5 .

**Comment by EdVince** [comment]
Anyway, this is just a prototype, so it has a lot of shortcomings. My development was carried out based on 32G windows 11.
