### ISSUE TITLE
512*512输出全黑的图片

### ISSUE THREAD

**Issue by Ijustakid** [EdVince/Stable-Diffusion-NCNN#36]
我把assets的文件换成了google driver中512的param
AutoencoderKL-256-fp16-opt.param -> AutoencoderKL-512-fp16-opt.param
UNetModel-256-MHA-fp16-opt.param -> UNetModel-512-MHA-fp16-opt.param
把code中也对应改成了这两个model
-       net.load_param(mgr,"AutoencoderKL-256-fp16-opt.param");
+       net.load_param(mgr,"AutoencoderKL-512-fp16-opt.param");

-       net.load_param(mgr,"UNetModel-256-MHA-fp16-opt.param");
+       net.load_param(mgr,"UNetModel-512-MHA-fp16-opt.param");

把MainActivity.java中的bitmap改为512
-        showBitmap = Bitmap.createBitmap(256,256,Bitmap.Config.ARGB_8888);
+        showBitmap = Bitmap.createBitmap(512,512,Bitmap.Config.ARGB_8888);

-                        showBitmap = Bitmap.createScaledBitmap(tmp,256,256,false);
+                        showBitmap = Bitmap.createScaledBitmap(tmp,512,512,false);

-        final int REQUIRED_SIZE = 256;
+        final int REQUIRED_SIZE = 512;

还有/android/app/src/main/jni/makeup_jni.cpp中的
-    cv::Mat image(256, 256, CV_8UC3);
+    cv::Mat image(512, 512, CV_8UC3);

-    cv::Mat image(256, 256, CV_8UC3);
+    cv::Mat image(512, 512, CV_8UC3);

我点APK中的txt2img后，会生成一张全黑的图像，step=15，seed=0，这是什么问题导致的呢？
或者有什么办法可以生成512*512 size的图像

Thanks.

**Comment by EdVince** [comment]
android里面的代码又一些地方的shape被我写死了，你得自己改一下。
