### ISSUE TITLE
Upload model to the repo

### ISSUE THREAD

**Issue by fengwang** [EdVince/Stable-Diffusion-NCNN#4]
It is difficult to download the model files outside China. Can you please upload a copy to github? I think it is easy to do  with lfs. Or upload a copy in the release.

**Comment by fengwang** [comment]
I forked your repo, downloaded the model files and then put those files in the forked repo [maintained with git-lfs](https://github.com/fengwang/Stable-Diffusion-NCNN/tree/main/assets).
But unfortunately I have to make it standalone as LFS is not supported in a publicly forked project.

**Comment by EdVince** [comment]
Thank you for your interest in my project. Considering that LFS has a capacity cap, I wouldn't always want to upload it there. I've updated the download link for Google Drive in the README and I think this can help you. And you have reminded me that maybe I need to write an English README to help people outside of China.
