### ISSUE TITLE
img2img缺少AutoencoderKL-encoder-256-256-fp16.param和AutoencoderKL-encoder-fp16.bin文件

### ISSUE THREAD

**Issue by LHB116** [EdVince/Stable-Diffusion-NCNN#52]
如题，android运行img2img时闪退，经过debug发现缺少AutoencoderKL-encoder-256-256-fp16.param和AutoencoderKL-encoder-fp16.bin文件，百度网盘和谷歌链接里没看到呀

**Comment by EdVince** [comment]
你是直接运行我提供的aok，还是自己用android代码编译的呀？

**Comment by LHB116** [comment]
> 你是直接运行我提供的aok，还是自己用android代码编译的呀？

我是用Android代码编译的，网盘和google里没找到这俩文件，后面用你release的apk解压出来了
