### ISSUE TITLE
A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x90bf400 in tid 15536 (.tencent.makeup), pid 15506 (.tencent.makeup)

### ISSUE THREAD

**Issue by imistyrain** [EdVince/Stable-Diffusion-NCNN#8]
android端编译通过后点CPU报错

 E/SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length

**Comment by EdVince** [comment]
你下了那三个bin模型到assets文件夹了吗？是一点就报错吗，因为用了三个模型，要看一下是哪里的错，还有就是你机子是多少内存的？

**Comment by imistyrain** [comment]
没有. 内存8G.
把三个模型加进去好了
