### ISSUE TITLE
models

### ISSUE THREAD

**Issue by hubin858130** [EdVince/Stable-Diffusion-NCNN#9]
Hello，大神，我想用dreamlike、Anything或者是自己炼的ckpt模型，转成onnx后，再怎么操作得到ncnn到模型和量化到fp16？onnx2ncnn 和 ncnnoptimize么？

**Comment by hubin858130** [comment]
[ncnn](https://github.com/Tencent/ncnn)

**Comment by hubin858130** [comment]
[Tencent/ncnn](https://github.com/Tencent/ncnn)当前master版本，还有Release里面的[20221128 03550ba](https://github.com/Tencent/ncnn/releases/tag/20221128)版本，每一步运行时间都是你android工程里面自带的ncnn的两倍，你是单独针对工程里面的ncnn库做了优化么？

**Comment by EdVince** [comment]
是的，安卓工程里的ncnn库有一些是还没合并到官方ncnn里的代码。

**Comment by ferqui** [comment]
Hi, are there any plans to release a version that uses the standard stable diffusion instead of naifu? Or create a documentation about how to export a model into NCNN? Thanks a lot!

**Comment by EdVince** [comment]
> Hi, are there any plans to release a version that uses the standard stable diffusion instead of naifu? Or create a documentation about how to export a model into NCNN? Thanks a lot!

no, I have no plan to export any more diffusion model. If you want to export any by yourselves, I advise you using the huggingface/diffusers.
